FROM node:20-alpine AS build

# make the 'app' folder the current working directory
WORKDIR /app

# install project dependencies
COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist .
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/entrypoint.sh .

RUN ["chmod", "+x", "/usr/share/nginx/html/entrypoint.sh"]

ENTRYPOINT ["/usr/share/nginx/html/entrypoint.sh"]

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]