export enum WeatherCode {
  ClearSky = 0,
  MainlyClear = 1,
  PartlyCloudy = 2,
  FewClouds = 3,
  ScatteredClouds = 4,
  BrokenClouds = 5,
  Overcast = 6,
  LightRain = 7,
  LightRainShowers = 8,
  ModerateRain = 9,
  ModerateRainShowers = 10,
  HeavyRain = 11,
  HeavyRainShowers = 12,
  LightSnow = 13,
  LightSleet = 14,
  LightSnowShowers = 15,
  LightSleetShowers = 16,
  ModerateSnow = 17,
  ModerateSleet = 18,
  HeavySnow = 19,
  HeavySleet = 20,
  LightFreezingRain = 21,
  LightFreezingDrizzle = 22,
  ModerateFreezingRain = 23,
  ModerateFreezingDrizzle = 24,
  LightFreezingFog = 25,
  ModerateFreezingFog = 26,
  LightFog = 27,
  ModerateFog = 28,
  Fog = 29,
  Drizzle = 30,
  LightDrizzle = 31,
  HeavyDrizzle = 32,
  FreezingDrizzle = 33,
  LightFreezingDrizzle_Alt = 34,
  HeavyFreezingDrizzle = 35,
  StrongThunderstorms = 36,
  Thunderstorms = 40,
  ThunderstormsWithHail = 41,
  LightThunderstorms = 44,
  FreezingRain = 48,
  FreezingFog = 50,
  Unstable = 51,
  Clear = 54,
  Cloudy = 56,
}

export const weatherIcons: { [key: number]: string } = {
  [WeatherCode.ClearSky]: 'wi-day-sunny.svg',
  [WeatherCode.MainlyClear]: 'wi-day-sunny-overcast.svg',
  [WeatherCode.PartlyCloudy]: 'wi-day-cloudy.svg',
  [WeatherCode.FewClouds]: 'wi-cloud.svg',
  [WeatherCode.ScatteredClouds]: 'wi-cloudy.svg',
  [WeatherCode.BrokenClouds]: 'wi-cloudy-gusts.svg',
  [WeatherCode.Overcast]: 'wi-cloudy-windy.svg',
  [WeatherCode.LightRain]: 'wi-rain.svg',
  [WeatherCode.LightRainShowers]: 'wi-showers.svg',
  [WeatherCode.ModerateRain]: 'wi-rain-wind.svg',
  [WeatherCode.ModerateRainShowers]: 'wi-showers.svg',
  [WeatherCode.HeavyRain]: 'wi-storm-showers.svg',
  [WeatherCode.HeavyRainShowers]: 'wi-storm-showers.svg',
  [WeatherCode.LightSnow]: 'wi-snow.svg',
  [WeatherCode.LightSleet]: 'wi-sleet.svg',
  [WeatherCode.LightSnowShowers]: 'wi-snow-wind.svg',
  [WeatherCode.LightSleetShowers]: 'wi-sleet.svg',
  [WeatherCode.ModerateSnow]: 'wi-snow.svg',
  [WeatherCode.ModerateSleet]: 'wi-sleet.svg',
  [WeatherCode.HeavySnow]: 'wi-snowflake-cold.svg',
  [WeatherCode.HeavySleet]: 'wi-sleet.svg',
  [WeatherCode.LightFreezingRain]: 'wi-rain-mix.svg',
  [WeatherCode.LightFreezingDrizzle]: 'wi-rain-mix.svg',
  [WeatherCode.ModerateFreezingRain]: 'wi-rain-mix.svg',
  [WeatherCode.ModerateFreezingDrizzle]: 'wi-rain-mix.svg',
  [WeatherCode.LightFreezingFog]: 'wi-fog.svg',
  [WeatherCode.ModerateFreezingFog]: 'wi-fog.svg',
  [WeatherCode.LightFog]: 'wi-fog.svg',
  [WeatherCode.ModerateFog]: 'wi-fog.svg',
  [WeatherCode.Fog]: 'wi-fog.svg',
  [WeatherCode.Drizzle]: 'wi-sprinkle.svg',
  [WeatherCode.LightDrizzle]: 'wi-sprinkle.svg',
  [WeatherCode.HeavyDrizzle]: 'wi-rain.svg',
  [WeatherCode.FreezingDrizzle]: 'wi-rain-mix.svg',
  [WeatherCode.LightFreezingDrizzle_Alt]: 'wi-rain-mix.svg',
  [WeatherCode.HeavyFreezingDrizzle]: 'wi-rain.svg',
  [WeatherCode.StrongThunderstorms]: 'wi-thunderstorm.svg',
  [WeatherCode.Thunderstorms]: 'wi-thunderstorm.svg',
  [WeatherCode.ThunderstormsWithHail]: 'wi-hail.svg',
  [WeatherCode.LightThunderstorms]: 'wi-thunderstorm.svg',
  [WeatherCode.FreezingRain]: 'wi-rain-mix.svg',
  [WeatherCode.FreezingFog]: 'wi-fog.svg',
  [WeatherCode.Unstable]: 'wi-alien.svg',
  [WeatherCode.Clear]: 'wi-day-sunny.svg',
  [WeatherCode.Cloudy]: 'wi-cloudy.svg',
}

export const DEFAULT_ICON = 'wi-day-sunny.svg'
